# Meeting agent default configuration
stt:
  backend: whisper
  model: small
  diarization: false
summary:
  backend: llm
  model: gpt-4o-mini
  temperature: 0.3
storage:
  output_root: data/meetings
  policy_tag: meeting_default

# Add per-folder overrides via smart folder policies (agents: ["meeting"])
