# Photo agent default configuration
embedding:
  backend: placeholder
  prefer_gpu: false
  batch_size: 32

similarity:
  duplicate_threshold: 0.95
  similar_threshold: 0.85

storage:
  output_root: data/photos
  policy_tag: photo_default
