artifact_location: file:///Users/david/Desktop/python/github/AI-summary/scripts/pipeline/.mlruns/518673880905714114
creation_time: 1765728740020
experiment_id: '518673880905714114'
last_update_time: 1765728740020
lifecycle_stage: active
name: AI-summary
