artifact_uri: file:///Users/david/Desktop/python/github/AI-summary/.mlruns/468460541132641232/21a563eb8de94a418cbc0b69fbbbcbd6/artifacts
end_time: 1765874523031
entry_point_name: ''
experiment_id: '468460541132641232'
lifecycle_stage: active
run_id: 21a563eb8de94a418cbc0b69fbbbcbd6
run_name: chat
run_uuid: 21a563eb8de94a418cbc0b69fbbbcbd6
source_name: ''
source_type: 4
source_version: ''
start_time: 1765874485638
status: 3
tags: []
user_id: david
